apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS {{ .Values.mysql.database }} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    USE {{ .Values.mysql.database }};

    CREATE TABLE IF NOT EXISTS clientes (
      id INT AUTO_INCREMENT PRIMARY KEY,
      nombre VARCHAR(100) NOT NULL,
      apellidos VARCHAR(100) NOT NULL,
      ciudad VARCHAR(100) NOT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

    INSERT INTO clientes (nombre, apellidos, ciudad) VALUES
      ('Juan',    'Pérez García',    'Monterrey'),
      ('María',   'López Hernández', 'Guadalajara'),
      ('Carlos',  'Ramírez Torres',  'CDMX'),
      ('Ana',     'Sánchez Ruiz',    'Puebla'),
      ('Luis',    'Gómez Castillo',  'Querétaro'),
      ('Sofía',   'Martínez Díaz',   'Mérida');
